-- STUDIO JOYO BARU 2 — Supabase database
-- Jalankan seluruh file ini di Supabase SQL Editor.

create table if not exists public.sjb_settings (
  id bigint primary key generated always as identity,
  store_name text not null default 'STUDIO JOYO BARU 2',
  store_sub text not null default 'PHOTO • PRINTING • COPY CENTER',
  phone text default '0857 4826 5687',
  address text default 'Graha Suko Indah No. 1A, Sukolegok, Sukodono, Sidoarjo',
  hours text default '07.00 WIB – 22.00 WIB',
  updated_at timestamptz not null default now()
);

create table if not exists public.sjb_services (
  id bigint generated by default as identity primary key,
  category text not null,
  name text not null,
  unit text not null default 'pcs',
  price numeric(14,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sjb_transactions (
  id uuid primary key default gen_random_uuid(),
  invoice text not null unique,
  transaction_date timestamptz not null default now(),
  due_date timestamptz,
  customer text default '',
  phone text default '',
  payment text not null default 'Lunas',
  channel text not null default 'Kasir',
  status text not null default 'Menunggu',
  discount numeric(14,2) not null default 0,
  total numeric(14,2) not null default 0,
  items jsonb not null default '[]'::jsonb,
  archived boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sjb_settings enable row level security;
alter table public.sjb_services enable row level security;
alter table public.sjb_transactions enable row level security;

-- Semua akses aplikasi harus melalui akun Supabase Auth.
-- Jangan gunakan service_role key di browser.
create policy "authenticated can read settings"
on public.sjb_settings for select to authenticated using (true);
create policy "authenticated can insert settings"
on public.sjb_settings for insert to authenticated with check (true);
create policy "authenticated can update settings"
on public.sjb_settings for update to authenticated using (true) with check (true);
create policy "authenticated can delete settings"
on public.sjb_settings for delete to authenticated using (true);

create policy "authenticated can read services"
on public.sjb_services for select to authenticated using (true);
create policy "authenticated can insert services"
on public.sjb_services for insert to authenticated with check (true);
create policy "authenticated can update services"
on public.sjb_services for update to authenticated using (true) with check (true);
create policy "authenticated can delete services"
on public.sjb_services for delete to authenticated using (true);

create policy "authenticated can read transactions"
on public.sjb_transactions for select to authenticated using (true);
create policy "authenticated can insert transactions"
on public.sjb_transactions for insert to authenticated with check (true);
create policy "authenticated can update transactions"
on public.sjb_transactions for update to authenticated using (true) with check (true);
create policy "authenticated can delete transactions"
on public.sjb_transactions for delete to authenticated using (true);

grant select, insert, update, delete on public.sjb_settings to authenticated;
grant select, insert, update, delete on public.sjb_services to authenticated;
grant select, insert, update, delete on public.sjb_transactions to authenticated;

insert into public.sjb_settings (store_name, store_sub, phone, address, hours)
select 'STUDIO JOYO BARU 2','PHOTO • PRINTING • COPY CENTER','0857 4826 5687','Graha Suko Indah No. 1A, Sukolegok, Sukodono, Sidoarjo','07.00 WIB – 22.00 WIB'
where not exists (select 1 from public.sjb_settings);

-- Nomor nota aman untuk multi-komputer.
create sequence if not exists public.sjb_invoice_seq start 1;

create or replace function public.sjb_next_invoice()
returns text
language sql
security invoker
as $$
  select 'SJB2-' || to_char(now() at time zone 'Asia/Jakarta','YYYYMMDD') || '-' ||
         lpad(nextval('public.sjb_invoice_seq')::text, 4, '0');
$$;

grant execute on function public.sjb_next_invoice() to authenticated;
